fix(ci): provide version with awk instead of yq

diff --git a/linux/snap/snapcraft.yaml b/linux/snap/snapcraft.yaml
--- a/linux/snap/snapcraft.yaml
+++ b/linux/snap/snapcraft.yaml
@@ -18,8 +18,8 @@ parts:
     source-depth: 1
     plugin: nil
     override-build: |
-      version=$(yq e '.version' pubspec.yaml | cut -d'+' -f1)
-      echo "version: $version"
+      version=$(awk '/version:/ { match($0, /[0-9]+\.[0-9]+\.[0-9]+\+/); print substr($0, RSTART, RLENGTH-1) }' pubspec.yaml)
+      if [[ -z "$version" ]]; then echo "Error: Failed to extract version from pubspec.yaml"; exit 1; fi; echo "Extracted version: $version"
       snapcraftctl set-version "$version"
       mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
       mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
@@ -65,7 +65,6 @@ parts:
 
   colors-ai:
     after: [flutter-git]
-    build-snaps: [yq]
     plugin: nil
     source: .
     stage-packages:
@@ -74,8 +73,8 @@ parts:
       - libsecret-1-0
     override-build: |
       set -eux
-      version=$(yq e '.version' pubspec.yaml | cut -d'+' -f1)
-      echo "version: $version"
+      version=$(awk '/version:/ { match($0, /[0-9]+\.[0-9]+\.[0-9]+\+/); print substr($0, RSTART, RLENGTH-1) }' pubspec.yaml)
+      if [[ -z "$version" ]]; then echo "Error: Failed to extract version from pubspec.yaml"; exit 1; fi; echo "Extracted version: $version"
       snapcraftctl set-version "$version"
       flutter channel stable
       flutter upgrade
